# vis.mac
# Macro to initialize visualization

# Select the visualization driver
/vis/open OGL 800x600-0+0

# Set viewing properties
/vis/viewer/set/viewpointThetaPhi 70. 20.
/vis/viewer/zoom 1.4
/vis/drawVolume

# Display the frame
/vis/scene/add/axes 0.0 0.0 0.0 10. cm
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate 1000

# Set style
/vis/scene/add/hits
/vis/modeling/trajectories/create/drawByCharge

# Update viewer
/vis/viewer/update
